-- task_4.sql
-- Script to show table structure without using DESCRIBE/EXPLAIN

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_KEY,
    COLUMN_DEFAULT
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_NAME = 'books'
    AND TABLE_SCHEMA = DATABASE();